Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.define "localvalidation" do |config|
    config.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      # vb.gui = true

      # Customize the amount of memory on the VM:
      vb.memory = "2048"
      vb.cpus = "2"
      vb.name = "validation-trusty"
    end
  end
  #config.vm.provision "shell", inline: $script, privileged: false
  config.vm.provision "shell", path: "provision.sh", privileged: false

  # config.vm.network "forwarded_port", guest: 80, host: 8000
  # config.vm.network "public_network"
end
