$script = <<SCRIPT
sudo apt-get -y install python-pip git
sudo apt-get -y install python-dev libnetcdf-dev
sudo apt-get -y install gdal-bin lftp

sudo pip install suplemon

echo "Creating directories for validation data..."
mkdir -p validation/data/input/tmp
mkdir -p validation/data/output

echo "Setting up Python environment..."
sudo pip install virtualenvwrapper
export WORKON_HOME=~/.virtualenvs
echo '. /usr/local/bin/virtualenvwrapper.sh' >> ~/.bashrc
source ~/.bashrc
mkvirtualenv validation
# mkvirtualenv --system-site-packages validation
workon validation

pip install pyresample
pip install funcsigs
pip install numpy
pip install pandas
pip install netCDF4

echo "Cloning from Github..."
cd validation
git clone https://github.com/HelgeDMI/trollvalidation.git

add2virtualenv ./trollvalidation/

cd trollvalidation
# python trollvalidation/validations/ice_conc_validation.py

SCRIPT


Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    vb.name = "validation-trusty"
  end
  config.vm.provision "shell", inline: $script

  # config.vm.network "forwarded_port", guest: 80, host: 8000
  # config.vm.network "public_network"
end
